In [1]:
import pandas as pd
from utils.dirs import data_dir
from scripts.defaults import battery_codes

filepath = data_dir / "facilities.csv"##

facilities_df = pd.read_csv(filepath, on_bad_lines="skip")

facilities_df.head()

,Participant Code,Participant Name,Facility Code,Facility Class,System Size (MW),Remaining capacity from embedded generator (MW),Extracted At
0,ALCOA,Alcoa of Australia Limited,ALCOA_KW_IL,Non-Dispatchable Load,NaN,66.0,2026-08-04 06:30:17
1,ALCOA,Alcoa of Australia Limited,ALCOA_PNJ_IL,Non-Dispatchable Load,NaN,NaN,NaN
2,ALCOA,Alcoa of Australia Limited,ALCOA_WGP,Scheduled Facility,16.0,NaN,NaN
3,ALCOA,Alcoa of Australia Limited,ALCOA_WGP_IL,Non-Dispatchable Load,NaN,85.0,NaN
4,ALINTA,Alinta Sales Pty Ltd,ALINTA_PNJ_U1,Scheduled Facility,143.0,NaN,NaN

In [2]:
facilities_df.loc[facilities_df["Facility Code"].isin(battery_codes)]

,Participant Code,Participant Name,Facility Code,Facility Class,System Size (MW),Remaining capacity from embedded generator (MW),Extracted At
6,ALINTA,Alinta Sales Pty Ltd,ALINTA_WGP_ESR1,Scheduled Facility,200.000,NaN,NaN
20,COL_BESS,Collie Battery Pty Ltd ATF Collie Battery Trust,COLLIE_BESS2,Scheduled Facility,600.000,NaN,NaN
21,COL_BESS,Collie Battery Pty Ltd ATF Collie Battery Trust,COLLIE_ESR1,Scheduled Facility,400.000,NaN,NaN
22,SBSOLAR1,Cunderdin Development Pty Ltd,SBSOLAR1_CUNDERDIN_PV1,Semi-Scheduled Facility,100.000,NaN,NaN
125,PRDSO,PRD SWIS OPS PTY LTD,PRDSO_WALPOLE_HG1,Non-Scheduled Facility,1.500,NaN,NaN
138,WPGENER,Synergy,COLLIE_ESR4,Scheduled Facility,500.000,NaN,NaN
139,WPGENER,Synergy,COLLIE_ESR5,Scheduled Facility,500.000,NaN,NaN
144,WPGENER,Synergy,KWINANA_ESR1,Scheduled Facility,200.000,NaN,NaN
145,WPGENER,Synergy,KWINANA_ESR2,Scheduled Facility,450.000,NaN,NaN
165,TSLA_MGT,Tesla Corporation Management Pty Ltd,TESLA_PICTON_G1,Scheduled Facility,9.999,NaN,NaN

In [3]:
df = pd.read_csv("wemde_fields.csv")
df.head()

,dataset,folder_url,source_file,member_file,kind,path,types,occurrences,position,read_status,example
0,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$,object,1.0,NaN,plateau,NaN
1,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data,object,1.0,NaN,plateau,NaN
2,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData,array,1.0,NaN,plateau,NaN
3,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[],object,7.0,NaN,plateau,NaN
4,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[].constraintLookUp,object,7.0,NaN,plateau,NaN

In [4]:
search_terms = [
    "bess",
    "ess",
    "esr",
    "battery",
    "capacity",
    "storage",
    "charge",
    "soc",
    "mwh",
    "energy",
    "bidirectional"
]

In [5]:
def matches(path):
    p = path.lower()
    return any(t in p for t in search_terms)

result = df[df["path"].apply(matches)]
result.head()

,dataset,folder_url,source_file,member_file,kind,path,types,occurrences,position,read_status,example
5,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[].constraintLookUp.forecast.en...,number,7.0,NaN,plateau,173.5770000000
6,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[].constraintLookUp.forecast.en...,number,7.0,NaN,plateau,2439.1130000000
7,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[].constraintLookUp.forecast.en...,number,7.0,NaN,plateau,2467.5270000000
8,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[].constraintLookUp.forecast.en...,number,7.0,NaN,plateau,2410.6980000000
9,caseInputData,https://data.wa.aemo.com.au/public/market-data...,ReferenceDispatchCase_202608040800.json,NaN,json,$.data.caseData[].constraintLookUp.forecast.es...,number,7.0,NaN,plateau,131.5645000000

In [22]:
result[["dataset", "kind", "path", "example"]]

,dataset,kind,path,example
5,caseInputData,json,$.data.caseData[].constraintLookUp.forecast.en...,173.5770000000
6,caseInputData,json,$.data.caseData[].constraintLookUp.forecast.en...,2439.1130000000
7,caseInputData,json,$.data.caseData[].constraintLookUp.forecast.en...,2467.5270000000
8,caseInputData,json,$.data.caseData[].constraintLookUp.forecast.en...,2410.6980000000
9,caseInputData,json,$.data.caseData[].constraintLookUp.forecast.es...,131.5645000000
...,...,...,...,...
1527,tradingReport,json,$.data.energyUpliftPricesAndUpliftPaymentMispr...,0
1547,tradingReport,json,$.data.networkLowerRiskCalculations[].networkL...,NaN
1548,tradingReport,json,$.data.networkLowerRiskCalculations[].networkL...,WEST_KALGOORLIE_GT3
1556,tradingReport,json,$.data.networkRiskCalculations[].networkRisks[...,NaN
1557,tradingReport,json,$.data.networkRiskCalculations[].networkRisks[...,ALINTA_WGP_U2