In [1]:
import pandas as pd
from utils.dirs import data_dir

filepath = data_dir / "facilities.csv"

facilities_df = pd.read_csv(filepath, on_bad_lines="skip")

facilities_df.head()

,Participant Code,Participant Name,Facility Code,Facility Class,System Size (MW),Remaining capacity from embedded generator (MW),Extracted At
0,ALCOA,Alcoa of Australia Limited,ALCOA_KW_IL,Non-Dispatchable Load,NaN,66.0,2026-08-04 06:30:17
1,ALCOA,Alcoa of Australia Limited,ALCOA_PNJ_IL,Non-Dispatchable Load,NaN,NaN,NaN
2,ALCOA,Alcoa of Australia Limited,ALCOA_WGP,Scheduled Facility,16.0,NaN,NaN
3,ALCOA,Alcoa of Australia Limited,ALCOA_WGP_IL,Non-Dispatchable Load,NaN,85.0,NaN
4,ALINTA,Alinta Sales Pty Ltd,ALINTA_PNJ_U1,Scheduled Facility,143.0,NaN,NaN

In [10]:
df = facilities_df[["Facility Code", "Facility Class", "System Size (MW)"]]
df.head()

   Facility Code         Facility Class  System Size (MW)
0    ALCOA_KW_IL  Non-Dispatchable Load               NaN
1   ALCOA_PNJ_IL  Non-Dispatchable Load               NaN
2      ALCOA_WGP     Scheduled Facility              16.0
3   ALCOA_WGP_IL  Non-Dispatchable Load               NaN
4  ALINTA_PNJ_U1     Scheduled Facility             143.0

In [11]:
battery_codes = [
    "COLLIE_BESS2",
    "COLLIE_ESR1",
    "COLLIE_ESR4",
    "COLLIE_ESR5",
    "KWINANA_ESR1",
    "KWINANA_ESR2",
    "SBSOLAR1_CUNDERDIN_PV1",
    "TESLA_PICTON_G1",
    "PRDSO_WALPOLE_HG1",  # fuel type: hydro
]

In [13]:
df.loc[df["Facility Code"].isin(battery_codes)]

              Facility Code           Facility Class  System Size (MW)
20             COLLIE_BESS2       Scheduled Facility           600.000
21              COLLIE_ESR1       Scheduled Facility           400.000
22   SBSOLAR1_CUNDERDIN_PV1  Semi-Scheduled Facility           100.000
125       PRDSO_WALPOLE_HG1   Non-Scheduled Facility             1.500
138             COLLIE_ESR4       Scheduled Facility           500.000
139             COLLIE_ESR5       Scheduled Facility           500.000
144            KWINANA_ESR1       Scheduled Facility           200.000
145            KWINANA_ESR2       Scheduled Facility           450.000
165         TESLA_PICTON_G1       Scheduled Facility             9.999